version: '3.8'

services:
  # Serviço para o MySQL
  mysql:
    image: mysql:8.0
    container_name: mysql_database
    ports:
      - "3307:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbrenttavel
      MYSQL_USER: senac
      MYSQL_PASSWORD: root
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./renttavel-backend/src/main/resources/scripts:/docker-entrypoint-initdb.d
  # Serviço para o Backend em Java
  java_app:
    build:
      context: ./renttavel-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql
  # Serviço para o Frontend em Angular
  angular_app:
    build:
      context: ./renttavel-frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - java_app
